### ISSUE TITLE
[Bug] Basics

### ISSUE THREAD

**Issue by imh0wie** [CertiKProject/certik-a-tour-of-solidity-tutorials#7]
1. [1.1 - C1.md] "...(TODO: inset link)..."

2. [1.4 - C4_final.sol] Though the instructions are asking user to "modify the function setYourFavoriteNumber so that unless the person calling the function sends 1 Ether, they will not be able to change the variable", the current solution is as following:

if( msg.value > 1 ether ) {
 ...
} 

3. [1.5 - C5.md] "Looking at the contract on the LEFT..."

4. [1.5 - C5.md]  Would it be better to mention the wrong way of setting up the function before the correct way of doing it?

**Comment by maxwellfoley3** [comment]
done
